# Generated by Django 4.2.6 on 2023-10-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reader',
            table='reader',
        ),
    ]
