# Generated by Django 4.2.6 on 2023-10-16 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0002_alter_reader_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_manager.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='loan_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи книги'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_manager.reader', verbose_name='Читатель'),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='first_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='last_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='middle_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Отчество'),
        ),
    ]
