# Generated by Django 4.2.6 on 2023-10-16 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0003_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='author',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='middle_name',
            field=models.CharField(max_length=100, verbose_name='Отчество'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name', 'middle_name')},
        ),
        migrations.AlterUniqueTogether(
            name='reader',
            unique_together={('first_name', 'last_name', 'middle_name')},
        ),
    ]
