# Generated by Django 4.2.6 on 2023-10-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0004_alter_author_first_name_alter_author_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
