# Generated by Django 4.2.6 on 2023-10-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_manager', '0005_book_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='code',
            field=models.IntegerField(blank=True, max_length=4, null=True, unique=True, verbose_name='Код'),
        ),
    ]
